apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication

metadata:
  name: customer-etl
  namespace: spark-jobs

spec:

  volumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName: spark-data-pvc

  timeToLiveSeconds: 600

  type: Python
  pythonVersion: "3"

  mode: cluster

  image: customer-etl:latest

  imagePullPolicy: IfNotPresent

  mainApplicationFile: local:///app/run_pipeline.py

  sparkVersion: "4.0.0"

  restartPolicy:
    type: Never

  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark

    securityContext:
    
    volumeMounts:
      - name: spark-data
        mountPath: /app/data/bronze
        subPath: bronze
      - name: spark-data
        mountPath: /app/data/hub
        subPath: hub
      - name: spark-data
        mountPath: /app/data/reject
        subPath: reject
      - name: spark-data
        mountPath: /app/data/mart
        subPath: mart

  executor:
    instances: 2
    cores: 1
    memory: "1g"

    securityContext:
    
    volumeMounts:
      - name: spark-data
        mountPath: /app/data/bronze
        subPath: bronze
      - name: spark-data
        mountPath: /app/data/hub
        subPath: hub
      - name: spark-data
        mountPath: /app/data/reject
        subPath: reject
      - name: spark-data
        mountPath: /app/data/mart
        subPath: mart